language: node_js

node_js:
 - "0.10"

env:
  global:
  - secure: "fYcS0GFLnkA6j+AXumJ1dzWF5yfKfLX9qA1+x12PNmkqosOHtZpF+P0QjUC4AcT2BXvo2s1AbNYrMwZGjEz23bFGou7YaOHkZ9GEp9XCDDKyt8QnELtiglIga+IVkKA3V2U+dlxuEI9LUmNzlLNeQYdDbrzEutFN3Q0PczDzSN0="
  - secure: "CQx2ix5qoqxqK640ADmKM2jesMeKLeo94SnMNfl86ozR/R5/bPwRHtWNeGsOhU7D4WhV3HtoS/8TZft7EAlz0uXT8TIMxceCDvw5aVBI6omXiFXAYcv0vIMyHbRmEVcQAHP6aTb7mRcauQT7shWt7e7XDFokr4no0F7crJLyXsM="

before_install:
 - sudo apt-get -y install python-pip
 - sudo pip install awscli

addons:
  firefox: "25.0"

script:
 - npm install grunt-cli -g
 - npm install
 - npm test
 - aws s3 cp --acl public-read dist/mapbox-gl.js s3://mapbox/mapbox-gl-js/${TRAVIS_BRANCH}/mapbox-gl.js
 - aws s3 cp --acl public-read dist/mapbox-gl-dev.js s3://mapbox/mapbox-gl-js/${TRAVIS_BRANCH}/mapbox-gl-dev.js
