language: node_js

node_js:
 - "0.10"

env:
  global:
  - secure: "JLNw0JyNufYo2tjuK5qzgEHIxOdKto7iOlzdWWw79h7CowgFsppH4ujOs9CqESuWMaIa9sVD8reYSfwO+2JvPb6gw3AFDbXRFGO7mVSgBx/UAPb6693h8LGo9DmIE/63x/J9qFdwM3ZCvVyR1Bv1h7Wef5Uzlbjc2U15jmvHcac="
  - secure: "OiZd9gUZQ/+YJio9/jguql8ZkLQSVHxaimXrSvBA0/gjuxQBv/tdAHa49OBiKcBccHnUZT/1p+05V1UlqR0h+t688yRMocsY4Ov4PgYXFBI/O8w2y/PuW+svDHyXBoBdn87GiPiCHB8t+FyYPIAak9D/KybOnIU+zEtc8FO5oPM="

before_install:
 - sudo apt-get -y install python-pip
 - sudo pip install awscli

addons:
  firefox: "25.0"

script:
 - npm install grunt-cli -g
 - npm install
 - npm test
 - aws s3 cp --acl public-read dist/llmr.js s3://mapbox/mapbox-gl-js/${TRAVIS_BRANCH}/mapbox-gl.js
 - aws s3 cp --acl public-read dist/llmr-dev.js s3://mapbox/mapbox-gl-js/${TRAVIS_BRANCH}/mapbox-gl-dev.js
