language: node_js
node_js:
- '0.10'
env:
  global:
  - secure: H2LKQIxHBV139kDLz4f3z7n/3g7890BbstLFaiHE1SBpOtxhEQonmTCY2oPp34Es9YeK01PxKMTIFsf5S3K7rERjUggJGE/XYDUN+TOUqX/JIPA26qF5sm+jJozDB7vF790uGg708/mrcV+uyent2olj7vwy7gYHykLmr8aiTPc=
  - secure: NDkXr7f3CFX9wDNUqtngbekeJ8u/PDQy6GdDAzoKcxN24L2ekJyg1heUjvRJNQTruzoWCtkU+tfrbrZ+J89jab6M20MAijWCy0NR5FiGlWUgsKzzmFPyZyRIbcj6vYXZn5FaN/7Bsh47DFSM0H0Z/M2w+02BXPnpMX+xCMMwBXE=
before_install:
- sudo apt-get -y install python-pip libglew-dev
- sudo pip install awscli
before_script:
- sh -e /etc/init.d/xvfb start
- export DISPLAY=:99.0
script:
- ./travis.sh
after_success:
- '[[ $TRAVIS_PULL_REQUEST = "false" ]] && ./deploy.sh $TRAVIS_BRANCH'
notifications:
  slack:
    secure: TA7WaU8eIhn5bRtv1loxHJ3smIT7sp6d/rmfh5P1DyVXjtVP87s1qXQGZoSBrMxS419eLMIZ+h768Y2PGde7ZeFsXbFn2b63tY75s2SLquYfh/tCdinPkwP4hVF0/QCk8flPX95mEkdXSiy53xas89rY7pojKKW2roMpjXLX7YY=
