ui: tape
browsers:
#  - name: chrome
#    version: latest
#    platform: "Mac 10.9"
  - name: firefox
    version: 30
    platform: "Windows 2012"
    firefox_profile:
      webgl.force-enabled: true
      webgl.disabled: false
      webgl.msaa-force: true
