source: docs
api: https://www.mapbox.com
url: https://www.mapbox.com
permalink: /mapbox-gl-js
baseurl: /mapbox-gl-js
highlighter: pygments
excerpt_separator: ""
version: v0.2.1
rdiscount:
  extensions: [smart]
