source: docs
api: https://www.mapbox.com
url: https://www.mapbox.com
permalink: /:categories/:title
baseurl: /mapbox-gl-js
highlighter: pygments
excerpt_separator: ""
version: v0.2.2
rdiscount:
  extensions: [smart]
