url: https://www.mapbox.com
api: https://www.mapbox.com
tileApi: https://api.tiles.mapbox.com
source: docs
permalink: /:categories/:title
baseurl: /mapbox-gl-js
highlighter: pygments
excerpt_separator: ""
version: v0.2.2
rdiscount:
  extensions: [smart]
