source: docs
api: https://122e4e-mapbox.global.ssl.fastly.net
url: https://122e4e-mapbox.global.ssl.fastly.net
permalink: ""
baseurl: ""
highlighter: pygments
excerpt_separator: ""
version: 0.0.15
mbglurl: https://api.tiles.mapbox.com/mapbox-gl-js/v0.1.0/mapbox-gl.js
rdiscount:
  extensions: [smart]