source: docs
api: https://122e4e-mapbox.global.ssl.fastly.net
url: https://122e4e-mapbox.global.ssl.fastly.net
permalink: /
baseurl: /
highlighter: true
version: 0.0.5
rdiscount:
  extensions: [smart]
