url: https://www.mapbox.com
api: https://www.mapbox.com/core
tileApi: https://api.tiles.mapbox.com
source: docs
permalink: /
baseurl: /mapbox-gl-style-spec
highlighter: true
version: 0.0.5
rdiscount:
  extensions: [smart]
