version: 2

workflows:
  version: 2
  default:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - release:
          requires:
            - build
          filters:
            tags:
              only: /.*/
jobs:
  build:
    docker:
      - image: mbgl/ci:r4-linux-gl-js
    working_directory: ~/mapbox-gl-js
    steps:
      - checkout
      - restore_cache:
          key: v1-mapbox-gl-js-cache
      - run:
          name: install dependencies
          command: yarn
      - save_cache:
          key: v1-mapbox-gl-js-cache
          paths:
            - '~/.yarn'
            - '.eslintcache'
            - 'node_modules'
      - run:
          name: run tests
          command: |
            bash ./.circleci/test.sh
      - store_artifacts:
          path: "test/integration/render-tests/index.html"
      - store_artifacts:
          path: "test/integration/query-tests/index.html"
  release:
    docker:
      - image: mbgl/ci:r4-linux-gl-js
    working_directory: ~/mapbox-gl-js
    steps:
      - checkout
      - restore_cache:
          key: v1-mapbox-gl-js-cache
      - run:
          name: install dependencies
          command: yarn
      - save_cache:
          key: v1-mapbox-gl-js-cache
          paths:
            - '~/.yarn'
            - '.eslintcache'
            - 'node_modules'
      - run:
          name: build-release
          command: yarn run build-min
      - run:
          name: deploy
          when: on_success
          command: bash ./.circleci/deploy.sh

